# Basic options
title: Regression Analysis with R
short_name: workshop-name
developers: Eilis Hannon
description: In this hands on workshop you will learn how to fit a range of regression models with R, how to interpret the output and the link between regression and other common statistical tools.
n_sessions: 1
prereq: Intoduction to R
url: https://uniexeterrse.github.io/intro-regression-with-r

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
